### ISSUE TITLE
Invalid Fields

### ISSUE THREAD

**Issue by bg-csaa** [mitiga/snowflake-extortion-campaign#1]
Could we get some clarification on some fields you are using in the queries shared? According to the documentation, you all have shared, there are a handful of fields that are not present in the documentation. Namely the most persistent is USER_NAME8. Because that field does not exist in the Snowflake documentation and is not defined in the queries themselves, I want to try and understand if this is just a typo from your own internal testing, if something was not defined that was supposed to be shared, or if I am missing something entirely. Thanks so much.

**Comment by Mitigian-Doron** [comment]
We have updated the queries to have the right fields along with a valid snowflake SQL.
